// List of suggestions (replace with your own data)
const suggestionsList = [
  "Tokyo",
  "Delhi",
  "Shanghai",
  "São Paulo",
  "Mumbai",
  "Mexico City",
  "Beijing",
  "Osaka",
  "Cairo",
  "New York City",
  "Dhaka",
  "Karachi",
  "Buenos Aires",
  "Istanbul",
  "Kolkata",
  "Manila",
  "Lagos",
  "Rio de Janeiro",
  "Tianjin",
  "Kinshasa",
  "Lahore",
  "Bangalore",
  "Paris",
  "Bogotá",
  "Chennai",
  "Jakarta",
  "Lima",
  "Bangkok",
  "Hyderabad",
  "London",
  "Nagoya",
  "Chicago",
  "Ho Chi Minh City",
  "Tehran",
  "Chongqing",
  "Shenzhen",
  "Essen",
  "Shenyang",
  "Hangzhou",
  "Suzhou",
  "Nanjing",
  "Wuhan",
  "Kuala Lumpur",
  "Johannesburg",
  "Taipei",
  "Hong Kong",
  "Hanoi",
  "Ahmedabad",
  "Toronto",
  "Baghdad",
  "Santiago",
  "Dallas",
  "Changsha",
  "Philadelphia",
  "Wenzhou",
  "Miami",
  "Shandong",
  "Belo Horizonte",
  "Houston",
  "Washington, D.C.",
  "Boston",
  "Linyi",
  "Luanda",
  "Pune",
  "Khartoum",
  "Seattle",
  "Guangzhou",
  "Kinshasa",
  "Riyadh",
  "Atlanta",
  "Singapore",
  "Saint Petersburg",
  "Sydney",
  "Surat",
  "Ankara",
  "Abidjan",
  "Jeddah",
  "Durban",
  "Yangon",
  "Alexandria",
  "Xiamen",
  "Jinan",
  "Ningbo",
  "Nairobi",
  "Dar es Salaam",
  "Melbourne",
  "Phoenix",
  "Berlin",
  "Monterrey",
  "Rome",
  "Medellín",
  "Kabul",
  "Athens",
  "Pyongyang",
  "Ekurhuleni",
  "Zhengzhou",
  "Surabaya",
  "Izmir",
  "Dubai",
  "Bucharest",
  "Caracas",
  "Mashhad",
  "Stockholm",
  "Kiev",
  "Nanchang",
  "Harbin",
  "Dalian",
  "Faisalabad",
  "Incheon",
  "Accra",
  "Tashkent",
  "Sana'a",
  "Bhopal",
  "San Francisco",
  "Montréal",
  "Naples",
  "Nagpur",
  "San Diego",
  "Jaipur",
  "Fortaleza",
  "Manaus",
  "Brisbane",
  "Salvador",
  "Durham",
  "Baku",
  "Kanpur",
  "Addis Ababa",
  "Curitiba",
  "Zibo",
  "Fuzhou",
  "Changzhou",
  "Budapest",
  "Valencia",
  "Kampala",
  "Kyoto",
  "Goiania",
  "Calgary",
  "Campinas",
  "Hamburg",
  "Medan",
  "Havana",
  "Belém",
  "Warsaw",
  "Riverside",
  "Lusaka",
  "Cincinnati",
  "Bursa",
  "Cleveland",
  "San Antonio",
  "Puebla",
  "Recife",
  "Gujranwala",
  "Vancouver",
  "Hefei",
  "Columbus",
  "Bucharest",
  "Omdurman",
  "Antananarivo",
  "Patna",
  "Valparaíso",
  "N'Djamena",
  "Wuxi",
  "Ibadan",
  "Brazzaville",
  "Gwangju",
  "Bishkek",
  "Taichung",
  "Kumasi",
  "Dakar",
  "Zaozhuang",
  "Tijuana",
  "Khulna",
  "San Jose",
  "Lubumbashi",
  "Fez",
  "Cape Town",
  "Benghazi",
  "Sofia",
  "Barranquilla",
  "Agra",
  "Tbilisi",
  "Quito",
  "Nagasaki",
  "La Paz",
  "Lilongwe",
  "Asunción",
  "Sapporo",
  "Lyon",
  "Antwerp",
  "Guadalajara",
  "Homs",
  "Bordeaux",
  "Daegu",
  "Rotterdam",
  "Kathmandu",
  "Zurich",
  "Yekaterinburg",
  "Palembang",
  "Kochi",
  "Irkutsk",
  "Jodhpur",
  "Gwalior",
  "Lome",
  "Makassar",
  "Luhansk",
  "Mbuji-Mayi",
  "Bandung",
  "Tirana",
  "Santiago de los Caballeros",
  "Manama",
  "Ulsan",
  "Mogadishu",
  "Niamey",
  "Newcastle",
  "Semarang",
  "Denpasar",
  "Gorakhpur",
  "Ludhiana",
  "Ottawa",
  "Hermosillo",
  "Acapulco",
  "Zagreb",
  "Blantyre",
  "Mysore",
  "Nicosia",
  "Thiruvananthapuram",
  "Vadodara",
  "Niigata",
  "Tiruchirappalli",
  "Salem",
  "Kollam",
  "Dushanbe",
  "Zhangjiakou",
  "Hail",
  "Londrina",
  "Huzhou",
  "Jhansi",
  "Kolhapur",
  "Xinxiang",
  "Córdoba",
  "Omsk",
  "Nantes",
  "Cancún",
  "Bogor",
  "Lodz",
  "Amman",
  "Sulaymaniyah",
  "Kisangani",
  "Vitória",
  "Ulan-Ude",
  "Rabat",
  "Hualien City",
  "Gdańsk",
  "León",
  "Djibouti",
  "Kirkuk",
  "Tongshan",
  "Balikpapan",
  "Oslo",
  "Samsun",
  "Santo Domingo Este",
  "Yichang",
  "Sukabumi",
  "Mwanza",
  "Hohhot",
  "Jiamusi",
  "Nashville",
  "Barranquilla",
  "Iquitos",
  "Naypyidaw",
  "Shizuoka",
  "Kagoshima",
  "Gorakhpur",
  "El Paso",
  "Tangier",
  "Ufa",
  "Ardabil",
  "Santa Fe",
  "Aden",
  "Tunis",
  "Astana",
  "Nampula",
  "Tlaxcala",
  "Tolyatti",
  "Gaziantep",
  "Makati",
  "Rasht",
  "Jiangmen",
  "Kermanshah",
  "Jeju City",
  "Mar del Plata",
  "Saida",
  "Cochabamba",
  "San Carlos de Bariloche",
  "Dunedin",
  "Goyang",
  "Yogyakarta",
  "Bilbao",
  "Gujarat",
  "Kerman",
  "Kuantan",
  "Ankara",
  "Osh",
  "Albuquerque",
  "Gaborone",
  "São José do Rio Preto",
  "Gazipur",
  "Tarija",
  "Biratnagar",
  "Corrientes",
  "Fukushima",
  "Udon Thani",
  "Fortaleza",
  "Hangu",
  "Juiz de Fora",
  "Hwaseong",
  "Rochester",
  "Mérida",
  "Santos",
  "Hai Phong",
  "Luoyang",
  "Port Sudan",
  "Irkutsk",
  "Kyzylorda",
  "Moradabad",
  "Villavicencio",
  "Maturín",
  "Béchar",
  "Kunduz",
  "Makassar",
  "Ipoh",
  "Raurkela",
  "Cape Coral",
  "Boa Vista",
  "Chernivtsi",
  "Yanbu",
  "Kuching",
  "Kabwe",
  "Vladivostok",
  "Qo‘qon",
  "Bauru",
  "Ambato",
  "Bahawalpur",
  "Mubi",
  "Monywa",
  "Ciudad Madero",
  "Akola",
  "Asyut",
  "Sétif",
  "Santo André",
  "San Fernando del Valle de Catamarca",
  "Tallinn",
  "Yaroslavl",
  "Pucallpa",
  "Ourense",
  "Tanjung Pinang",
  "Ryazan",
  "Neftekamsk",
  "Nizhnevartovsk",
  "Iquique",
  "Santa Rosa",
  "Rafsanjani",
  "Ussuriysk",
  "Saint-Denis",
  "Baranavichy",
  "Orsk",
  "Qianjiang",
  "Seremban",
  "Agadir",
  "Tacoma",
  "Kuala Terengganu",
  "Zamboanga City",
  "Muar",
  "Chlef",
  "Loja",
  "Batu Pahat",
  "Gusau",
  "Gilgit",
  "Pematangsiantar",
  "Puerto Princesa",
  "Bijapur",
  "Sibu",
  "Baghdad",
  "Kherson",
  "Boma",
  "Mzuzu",
  "Yulin",
  "Beira",
  "Palmas",
  "Sri Jayawardenepura Kotte",
  "Sylhet",
  "Piura",
  "Ribeirão Preto",
  "San Juan",
  "Kisumu",
  "Brahmapur",
  "Tembisa",
  "Kars",
  "Cikarang",
  "Gorontalo",
  "Nandyal",
  "Chiniot",
  "Teresina",
  "Gunsan",
  "Cheboksary",
  "Bridgetown",
  "Guntur",
  "Linxia",
  "Luhansk",
  "Lae",
  "Coimbra",
  "Bafoussam",
  "Mubi",
  "Bolu",
  "Marvdasht",
  "São Mateus",
  "Mansa",
  "Garoua",
  "Tanta",
  "Osogbo",
  "Kawagoe",
  "Parakou",
  "Masjed Soleyman",
  "Shimla",
  "Amol",
  "Bamako",
  "Kankan",
  "Klaipėda",
  "Ponta Grossa",
  "Kharagpur",
  "Arar",
  "Jeju City",
  "Cádiz",
  "Bahía Blanca",
  "Cirebon",
  "Belgorod",
  "Sumy",
  "Mbandaka",
  "Częstochowa",
  "Tumaco",
  "Yangju",
  "Rio Claro",
  "Dumaguete City",
  "Lashkar Gah",
  "Nampula",
  "Sari",
  "Kostroma",
  "Catanzaro",
  "Sekondi-Takoradi",
  "Hapur",
  "Ternopil",
  "Tébessa",
  "Tlemcen",
  "Namangan",
  "Jaipur",
  "Bafang",
  "Yopal",
  "Mangalore",
  "Gyeongsan",
  "Kashmar",
  "Santa Bárbara d'Oeste",
  "Gedaref",
  "Dijon",
  "Sanandaj",
  "Cork",
  "Sakakah",
  "Botoșani",
  "Mahabad",
  "Bắc Ninh",
  "Nashik",
  "Pereira",
  "Jhansi",
  "Kaluga",
  "Kaduna",
  "Damanhur",
  "Kulob",
  "Khenchela",
  "Puerto Montt",
  "Ar Raqqah",
  "Birjand",
  "Chittorgarh",
  "Chlef",
  "Salalah",
  "Kangar",
  "Ağrı",
  "Hạ Long",
  "Shushtar",
  "Portoviejo",
  "Nefteyugansk",
  "Pali",
  "Montes Claros",
  "Hami",
  "Novorossiysk",
  "Fuyang",
  "Rize",
  "Pamplona",
  "Saida",
  "Zielona Góra",
  "Tournai",
  "Lafiagi",
  "San Juan de la Maguana",
  "Chinandega",
  "Kolda",
  "Suzhou",
  "Batticaloa",
  "Kankan",
  "Acarigua",
  "Marília",
  "Yining",
  "Saïda",
  "Georgetown",
  "Butembo",
  "Lafayette",
  "Parbhani",
  "Vinh Long",
  "Bukhara",
  "Daloa",
  "Nakhon Si Thammarat",
  "Sangju",
  "Kalgoorlie-Boulder",
  "Ariana",
  "Jijel",
  "Hsinchu",
  "Kankan",
  "Sarh",
  "Arjona",
  "Punta Alta",
  "Chapayevsk",
  "Itumbiara",
  "Dolisie",
  "Medina",
  "Ereğli",
  "Tafí Viejo",
  "Zabol",
  "Fond du Lac",
  "Kohima",
  "Mudanjiang",
  "Grudziądz",
  "Viana",
  "Solapur",
  "Atyrau",
  "Caicó",
  "Touggourt",
  "Ardabil",
  "Kasserine",
  "Debre Birhan",
  "Osh",
  "Piracicaba",
  "Kanggye",
  "Saravan",
  "Sulaymaniyah",
  "Mouila",
  "Altamira",
  "Jyväskylä",
  "Ramallah",
  "Vinh Yên",
  "Iringa",
  "Kampong Chhnang",
  "Kamensk-Ural'skiy",
  "Dawei",
  "Saihat",
  "Sar-e Pol",
  "Huambo",
  "Parintins",
  "Guider",
  "Shinyanga",
  "Neftekamsk",
  "Mymensingh",
  "Chiclayo",
  "Kharan",
  "Girardot",
  "Bayamo",
  "Turbat",
  "Sibiu",
  "Garoua Boulaï",
  "Saint George",
  "Itapipoca",
  "Kapiri Mposhi",
  "Korhogo",
  "P'yŏngsŏng",
  "Phrae",
  "Songea",
  "Kasama",
  "Ondjiva",
  "Tulcea",
  "Sokodé",
  "Kumbo",
  "Wajir",
  "Taza",
  "Jataí",
  "Itacoatiara",
  "Fianarantsoa",
  "Miracema do Tocantins",
  "Serowe",
  "Jerez de García Salinas",
  "Jalapa",
  "Béja",
  "San Juan Bautista",
  "Nacala",
  "Nong Khai",
  "Nouakchott",
  "Narva",
  "Mufulira",
  "Bayombong",
  "Honiara",
  "Kandi",
  "Cuito",
  "Bac Lieu",
  "Chur",
  "Aswan",
  "Tumbes",
  "Saurimo",
  "San Cristóbal de las Casas",
  "Villa Nueva",
  "Sibolga",
  "Sukhothai",
  "Tuxpan",
  "Kolomna",
  "Kamina",
  "Mafeteng",
  "Ilam",
  "Fukui",
  "Golmud",
  "Manado",
  "Gashua",
  "Kabwe",
  "Sulmona",
  "Sari",
  "Dhamār",
  "Pereira Barreto",
  "Puerto Montt",
  "Akita",
  "Birni N Konni",
  "Gandajika",
  "Asella",
  "Budennovsk",
  "Parakou",
  "Boca do Acre",
  "Kamphaeng Phet",
  "Pombal",
  "Roma",
  "Kumul",
  "Kabul",
  "Serdar",
  "Sauraha",
  "Eenhana",
  "Gbarnga",
  "Namangan",
  "Gondomar",
  "Zarzis",
  "Kasulu",
  "Kara Balta",
  "Guarapari",
  "Aurora",
  "Igarapé-Miri",
  "Aragarças",
  "São Joaquim da Barra",
  "Kibaha",
  "Atar",
  "Mzuzu",
  "Mbinga",
  "Aksum",
  "Yola",
  "Néma",
  "Takamatsu",
  "Tivaouane",
  "Araguari",
  "Pak Phanang",
  "Gonder",
  "Bacabal",
  "Cao Lãnh",
  "Bulgan",
  "Kawambwa",
  "Cao Bằng",
  "Penedo",
  "Seoul",
  "Barra do Bugres",
  "Orekhovo-Zuyevo",
  "Foso",
  "Matsue",
  "Mumias",
  "Kilindoni",
  "Bafoulabé",
  "Moussoro",
  "Lào Cai",
  "Uige",
  "Narok",
  "Santa Rosalía",
  "Lukulu",
  "Dondo",
  "Pilar",
  "Akhisar",
  "Hai Phong",
  "Laï",
  "Levanger",
  "Rivas",
  "Cesena",
  "Lavras",
  "Gaalkacyo",
  "Sibiti",
  "Tura",
  "São Miguel dos Campos",
  "Nkhata Bay",
  "Tarragona",
  "Arzamas",
  "Kanoya",
  "Jaffna",
  "Bafata",
  "Fada Ngourma",
  "Chitipa",
  "Cà Mau",
  "Río Cuarto",
  "Tejen",
  "Abengourou",
  "Jaffarābād",
  "Vicuña",
  "Jalgaon",
  "Matagalpa",
  "Dadeldhurā",
  "Xudat",
  "Tulagi",
  "Moatize",
  "São João da Boa Vista",
  "Hrazdan",
  "Siem Reap",
  "Mahébourg",
  "Kukës",
  "Balkanabat",
  "Kununurra",
  "Ghardaïa",
  "Lamu",
  "Tuban",
  "Graaff-Reinet",
  "Tukrah",
  "Senanga",
  "Jérémie",
  "Benguela",
  "Yopal",
  "Gwanda",
  "San Rafael",
  "Goure",
  "Tabuk",
  "Kratié",
  "Nouakchott",
  "Kalabo",
  "Lira",
  "Morón",
  "Villa María",
  "Monywa",
  "Makeni",
  "Masis",
  "Kayes",
  "Dorud",
  "Wawa",
  "Hailar",
  "Al Aḩmadī",
  "Kapiri Mposhi",
  "As Salt",
  "Mashhad",
  "Moro",
  "Tshikapa",
  "Chinguitti",
  "Arujá",
  "Fuling",
  "Taveuni",
  "Saurimo",
  "Sauri",
  "Gobabis",
  "Kampong Chhnang",
  "Yenagoa",
  "Nusaybin",
  "Bajram Curri",
  "Macaé",
  "Puerto Carreño",
  "Puerto Cabezas",
  "Santiago del Estero",
  "Grimari",
  "Avarua",
  "El Tigre",
  "Gbarpolu",
  "Ōta",
  "Thái Nguyên",
  "Gorgol",
  "Nyahururu",
  "Kathmandu",
  "Boende",
  "Bua Yai",
  "Trujillo",
  "Kizlyar",
  "Thies",
  "Ceres",
  "San Carlos de Bariloche",
  "Malakal",
  "Viljandi",
  "Vila Real",
  "Tocoa",
  "Nan",
  "Elbląg",
  "Rosario",
  "Puerto Asís",
  "Naryn",
  "Sotouboua",
  "Oshakati",
  "Kolwezi",
  "Rio Branco",
  "Sanaa",
  "Caála",
  "Golfito",
  "Quelimane",
  "Koutiala",
  "Gokwe",
  "Kasempa",
  "Grajaú",
  "Nador",
  "Maun",
  "Capitán Bado",
  "Bridgetown",
  "Moroto",
  "El Geneina",
  "Valença",
  "Ouadda",
  "Yibin",
  "Sao Tome",
  "Gueckedou",
  "Mondulkiri",
  "Luena",
  "Mbabane",
  "Kavieng",
  "Pemba",
  "Kwekwe",
  "Yên Bái",
  "Cordoba",
  "Darhan",
  "La Serena",
  "Makokou",
  "Grytviken",
  "Kananga",
  "Rio Mayo",
  "Parepare",
  "Yen Bai",
  "Lakatoro",
  "Funtua",
  "Uva",
  "Barranca de Upía",
  "Anakao",
  "Tanjung Selor",
  "Ranau",
  "Tougan",
  "Bu'aale",
  "Guayaramerín",
  "Mbanza-Ngungu",
  "Sibiti",
  "Kankan",
  "Xinqing",
  "Kamina",
  "Qena",
  "Wum",
  "Bangolo",
  "Fiditi",
  "Uíge",
  "Bender Qassim",
  "Qaratau",
  "Qax",
  "Al Bayḑā’",
  "Thyolo",
  "Fomboni",
  "Téra",
  "Bacolod",
  "Ayacucho",
  "Coihaique",
  "Birao",
  "Nola",
  "Kovrov",
  "Puerto Natales",
  "Sharan",
  "Buala",
  "Lukulu",
  "Kavieng District",
  "Aysén",
  "Champoton",
  "Chitado",
  "Sauraha",
  "Quilpie",
  "Kontagora",
  "Serenje",
  "Tubuala",
  "Yelizovo",
  "El Dorado",
  "Bueng Kan",
  "Wajir",
  "Gamboma",
  "Kemijärvi",
  "Edd",
  "Bamfield",
  "Turukhansk",
  "Dimitrovgrad",
  "Obidos",
  "Makaryev",
  "Riobamba",
  "Pitalito",
  "Pedernales",
  "Kirakira",
  "Biltine",
  "Panguna",
  "Leposaviq",
  "Olga",
  "San Francisco",
  "Pamplona",
  "Bhurban",
  "Oroville",
  "Kibale",
  "Siuna",
  "Rundu",
  "Amderma",
  "Amahai",
  "Luau",
  "Viedma",
  "Kokoda",
  "Sukhothai",
  "Cabo Rojo",
  "Guanare",
  "Chimoio",
  "Dondo",
  "Taltal",
  "Ariquemes",
  "Chapais",
  "Lingayen",
  "Porlamar",
  "Picos",
  "Thaba-Tseka",
  "Janauba",
  "Gonbad-e Qabus",
  "Koidu",
  "Hawabango",
  "Lobatse",
  "Cuamba",
  "Mansa",
  "Tepalcatepec",
  "Andapa",
  "Kautokeino",
  "Ribeira Brava",
  "Yenagoa",
  "Alleppey",
  "Necochea",
  "Zongo",
  "Kamina Base",
  "Santa Fe",
  "Gobabis",
  "Wawa",
  "Sao Lourenco",
  "Sambava",
  "Iguape",
  "Dila",
  "Kumluca",
  "Dabola",
  "Santa Rosa",
  "Mandalgovi",
  "Lokossa",
  "Quang Tri",
  "Wahran",
  "San Francisco de Macoris",
  "Moyobamba",
  "Camocim",
  "Ocussi-Ambeno",
  "Kuryk",
  "Bokoro",
  "Kita",
  "Poya",
  "Lokichoggio",
  "Arba Minch",
  "Namanga",
  "Golmud",
  "Yen Vinh",
  "Nacala",
  "Nkhata Bay",
  "Aileu",
  "Taybad",
  "Stornoway",
  "Huarmey",
  "Khakasskaya",
  "Luang Namtha",
  "Tolanaro",
  "Cametá",
  "Cabinda",
  "Nusaybin",
  "Malange",
  "Nioro du Sahel",
  "Pangkalanbuun",
  "Eirunepe",
  "Lamu",
  "Baglung",
  "Kailahun",
  "Bol",
];
const input = document.getElementById("input");
const suggestions = document.getElementById("suggestions");
let mainUl = document.getElementById("suggestions");

function filterSuggestions() {
  if (input.value != "") {
    let inputText = input.value.toLocaleLowerCase();
    let filtersList = suggestionsList.filter((suggest) =>
      suggest.toLocaleLowerCase().startsWith(inputText)
    );
    showData(filtersList);
  }
}

function showData(data) {
  mainUl.innerHTML = "";
  for (let i = 0; i < data.length; i++) {
    let li = document.createElement("li");
    li.appendChild(document.createTextNode(data[i]));
    li.onclick = function () {
      input.value = li.textContent;
      mainUl.innerHTML = "";
    };
    mainUl.appendChild(li);
  }
}
input.oninput = function () {
  filterSuggestions();
  if (input.value == "") {
    mainUl.innerHTML = "";
  }
};
